version: "3.5"

services:
  traefik:
    image: traefik:v2.3
    container_name: "misskey-traefik"
    restart: always
    command:
      #      - "--log.level=DEBUG"
      - "--api.dashboard=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.letsencrypt.acme.email=${EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.keyType=EC256"
    ports:
      - "80:80"
      - "443:443"
    labels:
      - "traefik.enable=true"
      # Dashboard
      - "traefik.http.routers.traefik.rule=(Host(`${DOMAIN}`) && PathPrefix(`/traefik`))"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.middlewares=dashboardauth"
      - "traefik.http.middlewares.dashboardauth.basicauth.users=${TRAEFIK_DASHBOARD_ADMIN_PASSWORD}"
      # HTTPS Redirect
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https@docker"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    environment:
      - CLOUDFLARE_EMAIL=${CLOUDFLARE_EMAIL}
      - CLOUDFLARE_DNS_API_TOKEN=${CLOUDFLARE_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/letsencrypt
    networks:
      - external_network

  web:
    image: akarregi/misskey:12.108.1
    container_name: "misskey-fe"
    restart: always
    links:
      - db
      - redis
    depends_on:
      - traefik
      - db
      - redis
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=misskey_external_network"
      - "traefik.http.services.misskey-web.loadbalancer.server.port=3000"
      - "traefik.http.routers.misskey-web.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.misskey-web.entrypoints=websecure"
      - "traefik.http.routers.misskey-web.tls.certresolver=letsencrypt"
    volumes:
      - ./files:/misskey/files
      - ./configuration:/misskey/.config:ro
    networks:
      - internal_network
      - external_network

  redis:
    image: redis:4.0-alpine
    container_name: "misskey-redis"
    restart: always
    volumes:
      - ./redis:/data
    networks:
      - internal_network

  db:
    image: postgres:12.2-alpine
    container_name: "misskey-postgres"
    restart: always
    env_file:
      - configuration/docker.env
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - internal_network

  # nginx:
  #   restart: always
  #   image: nginx:latest
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.docker.network=misskey_external_network"
  #     - "traefik.http.services.misskey-media.loadbalancer.server.port=4000"
  #     - "traefik.http.routers.misskey-media.rule=Host(`${DOMAIN_MEDIA}`)"
  #     - "traefik.http.routers.misskey-media.entrypoints=websecure"
  #     - "traefik.http.routers.misskey-media.tls.certresolver=letsencrypt"
  #   depends_on:
  #     - traefik
  #   environment:
  #     - DOMAIN_MEDIA=${DOMAIN_MEDIA}
  #   volumes:
  #     - ./configuration/default.conf:/etc/nginx/conf.d/default.conf
  #   networks:
  #     - internal_network
  #     - external_network

networks:
  external_network:
    name: misskey_external_network
  internal_network:
    internal: true
